from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView, RedirectView
from . import views
urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.png', permanent=True), name="favicon_ico"),
    path('favicon.png', RedirectView.as_view(url='/static/favicon.png', permanent=True), name="favicon_png"),
    path('icon-192x192.png', RedirectView.as_view(url='/static/favicon.png', permanent=True), name="icon_192"),
    path('icon-512x512.png', RedirectView.as_view(url='/static/favicon.png', permanent=True), name="icon_512"),
    path("login/", views.login_view, name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page='login'), name="logout"),
    path("api/verify-token/", views.api_verify_token, name="api_verify_token"),
    path("api/save-fcm-token/", views.api_save_fcm_token, name="api_save_fcm_token"),
    path("", views.home_hub, name="home"),
    path("manifest.json", TemplateView.as_view(template_name="manifest.json", content_type="application/json"), name="manifest"),
    path("sw.js", TemplateView.as_view(template_name="sw.js", content_type="application/javascript"), name="sw"),
    path("match/", views.match_feed, name="match_feed"),
    path("more/", views.more_menu, name="more_menu"),
    path("complete_profile/", views.complete_profile, name="complete_profile"),
    path("save_profile_progress/", views.save_profile_progress, name="save_profile_progress"),
    path("verify/", views.verify, name="verify"),
    path("verify/skip/", views.skip_verification, name="skip_verification"),
    path("check_match/", views.check_match, name="check_match"),
    path("api/quiz/batch/", views.get_quiz_batch, name="get_quiz_batch"),
    path("api/quiz/save/", views.save_quiz_batch, name="save_quiz_batch"),
    path("answer_question/<int:question_id>/", views.answer_question, name="answer_question"),
    path("match/send/<int:receiver_id>/", views.send_match_request, name="send_match_request"),
    path("match/skip/<int:receiver_id>/", views.skip_match, name="skip_match"),
    path("match/accept/<int:req_id>/", views.accept_match, name="accept_match"),
    path("match/reject/<int:req_id>/", views.reject_match, name="reject_match"),
    path("connections/", views.connections_view, name="connections"),
    path("chat/get-or-create/", views.api_get_or_create_conversation, name="api_get_or_create_conversation"),
    path("chat/<int:partner_id>/", views.chat_view, name="chat_view"),
    path("chats/", views.chat_list_view, name="chat_list"),
    path("api/chat/<int:partner_id>/", views.chat_api_messages, name="chat_api_messages"),
    path("chat/typing/<int:partner_id>/", views.chat_typing, name="chat_typing"),
    path("chat/read/<int:partner_id>/", views.mark_messages_read, name="mark_messages_read"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    path("settings/", views.settings_view, name="settings"),
    path("api/test-push/", views.test_push, name="test_push"),
    path("settings/delete/", views.delete_account, name="delete_account"),
    path("profile/<int:user_id>/", views.view_profile, name="view_profile"),
    path("profile/spark/<int:user_id>/", views.toggle_spark, name="toggle_spark"),
    path("profile/toggle-discoverable/", views.toggle_discoverable, name="toggle_discoverable"),
    path("profile/block/<int:user_id>/", views.block_user, name="block_user"),
    path("chat/delete/<int:partner_id>/", views.delete_chat, name="delete_chat"),
    path("announcements/", views.announcements_view, name="announcements"),
    path("profile/image/delete/<int:image_id>/", views.delete_profile_image, name="delete_profile_image"),
    path("run_migrations/", views.run_migrations, name="run_migrations"),
    path("wall/", views.wall_view, name="wall"),
    path("api/wall/", views.wall_api, name="wall_api"),
    path("confessions/", views.confessions_feed, name="confessions_feed"),
    path("confessions/create/", views.create_confession, name="create_confession"),
    path("confessions/<int:confession_id>/", views.confession_detail, name="confession_detail"),
    path("confessions/<int:confession_id>/edit/", views.edit_confession, name="edit_confession"),
    path("confessions/<int:confession_id>/delete/", views.delete_confession, name="delete_confession"),
    path("confessions/<int:confession_id>/report/", views.report_confession, name="report_confession"),
    path("report/user/<int:user_id>/", views.report_user, name="report_user"),
    path("confessions/<int:confession_id>/comment/", views.add_comment, name="add_comment"),
    path("confessions/comments/<int:comment_id>/delete/", views.delete_comment, name="delete_comment"),
    path("confessions/<int:confession_id>/like/", views.like_confession, name="like_confession"),
    path("master/dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("master/dashboard/allusers", views.admin_all_users, name="admin_all_users"),
    path("master/dashboard/verification/", views.admin_manual_verification, name="admin_manual_verification"),
    path("master/dashboard/staffs/", views.admin_manage_staff, name="admin_manage_staff"),
    path("master/action/", views.admin_action, name="admin_action"),
    path("master/user/<int:user_id>/", views.admin_view_user, name="admin_view_user"),
    path("master/giveaway/control/", views.admin_giveaway_control, name="admin_giveaway_control"),
    path("master/profile/edit/<int:user_id>/", views.admin_edit_user_profile, name="admin_edit_user_profile"),
    path("giveaway/enter/", views.giveaway_entry, name="giveaway_entry"),
    path("giveaway/", views.giveaway_page, name="giveaway_page"),
    path("api/movies/search/", views.search_movies, name="search_movies"),
    path("api/favorites/save/", views.save_favorites, name="save_favorites"),
    path("api/upload/base64/", views.upload_base64_api, name="upload_base64_api"),
    path("roomfinder/", views.roomfinder_feed, name="roomfinder_feed"),
    path("roomfinder/<int:id>/", views.roomfinder_detail, name="roomfinder_detail"),
    path("api/roomfinder/<int:id>/save/", views.api_toggle_save_room, name="api_toggle_save_room"),
    path("api/roomfinder/<int:id>/edit/", views.api_edit_room, name="api_edit_room"),
    path("api/roomfinder/<int:id>/delete/", views.api_delete_room, name="api_delete_room"),
    path("api/roomfinder/create/", views.api_create_room, name="api_create_room"),
    path("api/roomfinder/list/", views.api_get_rooms, name="api_get_rooms"),
    path("api/roomrequests/create/", views.api_create_room_request, name="api_create_room_request"),
    path("api/roomrequests/list/", views.api_get_room_requests, name="api_get_room_requests"),
    path("api/roomrequests/<int:id>/delete/", views.api_delete_room_request, name="api_delete_room_request"),
    path("api/roomrequests/<int:id>/edit/", views.api_edit_room_request, name="api_edit_room_request"),
    path("roomrequest/<int:id>/", views.roomrequest_detail, name="roomrequest_detail"),
    path("sitemap.xml", views.sitemap_view, name="sitemap"),
    path("robots.txt", views.robots_txt_view, name="robots_txt"),
]