# Generated by Django 5.2.4 on 2026-06-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_voiceroom_voiceparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceparticipant',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
