# Generated by Django 5.2.4 on 2026-06-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_voiceparticipant_last_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceparticipant',
            name='session_peer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
