# Generated by Django 5.2.4 on 2026-06-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_bugreport_featuresuggestion_feedbacknotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='unread',
            field=models.IntegerField(default=0),
        ),
    ]
