# Generated by Django 5.2.4 on 2026-06-21 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_advertisement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusSpotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_handle', models.CharField(max_length=100)),
                ('content_type', models.CharField(choices=[('vlog', 'Vlog'), ('blog', 'Blog'), ('photography', 'Photography'), ('art', 'Art'), ('music', 'Music'), ('fitness', 'Fitness'), ('tech', 'Tech'), ('fashion', 'Fashion'), ('other', 'Other')], max_length=50)),
                ('note', models.TextField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
