# Generated by Django 5.2.4 on 2026-06-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_campusspotlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusspotlight',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
