# Generated by Django 5.2.4 on 2026-06-23 18:39

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Event = apps.get_model('home', 'Event')
    import time
    for event in Event.objects.all():
        base = slugify(f"{event.campus} {event.title}") if event.campus else slugify(event.title)
        if not base:
            base = f"event-{event.id}"
        event.slug = base
        # check uniqueness
        while Event.objects.filter(slug=event.slug).exclude(pk=event.pk).exists():
            event.slug = f"{base}-{int(time.time())}"
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
